### ISSUE TITLE
Stages should be a hash, not string

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-data-iho#2]
We have `abbreviation` optional attribute in `status/stage` and `status/substage` elements. So in YAML format it is:
```yaml
...
docstatus:
  stage:
    value: in-force
    abbreviation: IF
...
```

**Comment by ronaldtse** [comment]
Agree, please help fix https://github.com/metanorma/metanorma-model-iho and file a ticket at metanorma-iho. Thanks.

**Comment by andrew2net** [comment]
@ronaldtse I think there is no to change in the metanorma-model-iho. The change affects on YAML files in this repo. Instead of:
```yaml
...
docstatus:
  stage: in-force
...
```
we should use:
```yaml
...
docstatus:
  stage:
    value: in-force
...
```
