### ISSUE TITLE
Properly set Part documents

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-iho#6]
These documents are parts:

* S-5A
* S-5B
* S-8A
* S-8B

They are now temporarily provided with a `partnumber:` but need to make sure it fits Relaton.

**Comment by andrew2net** [comment]
Isn't `partnumber` an element `part` of `structuredidentifier`?
```yaml
structuredidentifier:
  project_number: ISO 1-2:2014
  part: 2
  subpart: 2
  type: sid
```
described in the grammar as:
```
structuredidentifier = element structuredidentifier {
  attribute type { text }?,
  element agency { text }+,
  element class { text }?,
  element docnumber { text },
  element partnumber { text }?,
  element edition { text }?,
  element version { text }?,
  element supplementtype { text }?,
  element supplementnumber { text }?,
  element language { text }?,
  element year { text }?
}
```
