### ISSUE TITLE
Properly set Annex documents

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-data-iho#7]
These documents are Annexes of existing documents:

* S-65 Annex A

It is now temporarily provided with a `locality:` but need to make sure it fits Relaton.

**Comment by andrew2net** [comment]
for the top-level locality is called `extent` element:
```yaml
extent:
  - type: annex
    reference_from: S-65
    reference_to: A
  - type: chapter
    reference_from: 4
```
